# encoding: utf-8
Spree::Taxon.class_eval do

  def applicable_filters
    fs = []
	# case self.name
	#    when "Биде" 
	   	
	#    end   
    
    fs << Spree::Core::ProductFilters.price_filter if Spree::Core::ProductFilters.respond_to?(:price_filter)
    fs << Spree::Core::ProductFilters.select_brand_any(self) if Spree::Core::ProductFilters.respond_to?(:select_brand_any)
    fs << Spree::Core::ProductFilters.select_country_any(self) if Spree::Core::ProductFilters.respond_to?(:select_country_any)
    fs << Spree::Core::ProductFilters.select_width_any(self) if Spree::Core::ProductFilters.respond_to?(:select_width_any)
    fs << Spree::Core::ProductFilters.select_deep_any(self) if Spree::Core::ProductFilters.respond_to?(:select_deep_any)
    fs << Spree::Core::ProductFilters.select_height_any(self) if Spree::Core::ProductFilters.respond_to?(:select_height_any)
    fs << Spree::Core::ProductFilters.select_type_any(self) if Spree::Core::ProductFilters.respond_to?(:select_type_any)
    fs << Spree::Core::ProductFilters.select_shutter_type_any(self) if Spree::Core::ProductFilters.respond_to?(:select_shutter_type_any)
    fs << Spree::Core::ProductFilters.select_lattice_type_any(self) if Spree::Core::ProductFilters.respond_to?(:select_lattice_type_any)
    fs << Spree::Core::ProductFilters.select_bulk_any(self) if Spree::Core::ProductFilters.respond_to?(:select_bulk_any)
    fs << Spree::Core::ProductFilters.select_material_any(self) if Spree::Core::ProductFilters.respond_to?(:select_material_any)
    fs << Spree::Core::ProductFilters.select_corpus_material_any(self) if Spree::Core::ProductFilters.respond_to?(:select_corpus_material_any)
    fs << Spree::Core::ProductFilters.select_corpus_coating_any(self) if Spree::Core::ProductFilters.respond_to?(:select_corpus_coating_any)
    fs << Spree::Core::ProductFilters.select_fasade_material_any(self) if Spree::Core::ProductFilters.respond_to?(:select_fasade_material_any)
    fs << Spree::Core::ProductFilters.select_fasade_coating_any(self) if Spree::Core::ProductFilters.respond_to?(:select_fasade_coating_any)
    fs << Spree::Core::ProductFilters.select_tabletop_material_any(self) if Spree::Core::ProductFilters.respond_to?(:select_tabletop_material_any)
    fs << Spree::Core::ProductFilters.select_door_material_any(self) if Spree::Core::ProductFilters.respond_to?(:select_door_material_any)
    fs << Spree::Core::ProductFilters.select_lattice_material_any(self) if Spree::Core::ProductFilters.respond_to?(:select_lattice_material_any)
    fs << Spree::Core::ProductFilters.select_door_execution_any(self) if Spree::Core::ProductFilters.respond_to?(:select_door_execution_any)
    fs << Spree::Core::ProductFilters.select_forms_any(self) if Spree::Core::ProductFilters.respond_to?(:select_select_forms_any)
    fs << Spree::Core::ProductFilters.select_sink_form_any(self) if Spree::Core::ProductFilters.respond_to?(:select_sink_form_any)
    fs << Spree::Core::ProductFilters.select_color_any(self) if Spree::Core::ProductFilters.respond_to?(:select_color_any)
    fs << Spree::Core::ProductFilters.select_sink_color_any(self) if Spree::Core::ProductFilters.respond_to?(:select_sink_color_any)
    fs << Spree::Core::ProductFilters.select_montaj_any(self) if Spree::Core::ProductFilters.respond_to?(:select_montaj_any)
    fs << Spree::Core::ProductFilters.select_orientation_any(self) if Spree::Core::ProductFilters.respond_to?(:select_orientation_any)
    fs << Spree::Core::ProductFilters.select_appointment_any(self) if Spree::Core::ProductFilters.respond_to?(:select_appointment_any)
    fs << Spree::Core::ProductFilters.select_emission_direct_any(self) if Spree::Core::ProductFilters.respond_to?(:select_emission_direct_any)
    fs << Spree::Core::ProductFilters.select_appointment_any(self) if Spree::Core::ProductFilters.respond_to?(:select_appointment_any)
    fs << Spree::Core::ProductFilters.select_emission_direct_any(self) if Spree::Core::ProductFilters.respond_to?(:select_emission_direct_any)
    fs << Spree::Core::ProductFilters.select_door_for_any(self) if Spree::Core::ProductFilters.respond_to?(:select_door_for_any)
    fs << Spree::Core::ProductFilters.select_door_presence_any(self) if Spree::Core::ProductFilters.respond_to?(:select_door_presence_any)
    fs << Spree::Core::ProductFilters.select_control_any(self) if Spree::Core::ProductFilters.respond_to?(:select_control_any)
    fs << Spree::Core::ProductFilters.select_type_of_pallet_any(self) if Spree::Core::ProductFilters.respond_to?(:select_type_of_pallet_any)
    fs << Spree::Core::ProductFilters.select_hydromassage_any(self) if Spree::Core::ProductFilters.respond_to?(:select_hydromassage_any)
    fs << Spree::Core::ProductFilters.select_aeromassage_any(self) if Spree::Core::ProductFilters.respond_to?(:select_aeromassage_any)
    fs << Spree::Core::ProductFilters.select_turkish_bath_any(self) if Spree::Core::ProductFilters.respond_to?(:select_turkish_bath_any)
    fs << Spree::Core::ProductFilters.select_finnish_sauna_any(self) if Spree::Core::ProductFilters.respond_to?(:select_finnish_sauna_any)
    fs << Spree::Core::ProductFilters.select_backlight_any(self) if Spree::Core::ProductFilters.respond_to?(:select_backlight_any)
    fs << Spree::Core::ProductFilters.select_illumination_any(self) if Spree::Core::ProductFilters.respond_to?(:select_illumination_any)
    fs << Spree::Core::ProductFilters.select_built_in_seat_any(self) if Spree::Core::ProductFilters.respond_to?(:select_built_in_seat_any)
    fs << Spree::Core::ProductFilters.select_door_construction_any(self) if Spree::Core::ProductFilters.respond_to?(:select_door_construction_any)
    fs << Spree::Core::ProductFilters.select_hand_shower_any(self) if Spree::Core::ProductFilters.respond_to?(:select_hand_shower_any)
    fs << Spree::Core::ProductFilters.select_tropic_shower_any(self) if Spree::Core::ProductFilters.respond_to?(:select_tropic_shower_any)
    fs << Spree::Core::ProductFilters.select_seed_in_any(self) if Spree::Core::ProductFilters.respond_to?(:select_seed_in_any)
    fs << Spree::Core::ProductFilters.select_radio_any(self) if Spree::Core::ProductFilters.respond_to?(:select_radio_any)
    fs << Spree::Core::ProductFilters.select_seed_with_micro_any(self) if Spree::Core::ProductFilters.respond_to?(:select_seed_with_micro_any)
    fs << Spree::Core::ProductFilters.select_rimless_any(self) if Spree::Core::ProductFilters.respond_to?(:select_rimless_any)
    fs << Spree::Core::ProductFilters.select_bide_function_any(self) if Spree::Core::ProductFilters.respond_to?(:select_bide_function_any)
    fs << Spree::Core::ProductFilters.select_water_drain_mode_any(self) if Spree::Core::ProductFilters.respond_to?(:select_water_drain_mode_any)
    fs << Spree::Core::ProductFilters.select_attach_method_any(self) if Spree::Core::ProductFilters.respond_to?(:select_attach_method_any)
    fs << Spree::Core::ProductFilters.select_water_delivery_any(self) if Spree::Core::ProductFilters.respond_to?(:select_water_delivery_any)
    fs << Spree::Core::ProductFilters.select_wing_any(self) if Spree::Core::ProductFilters.respond_to?(:select_wing_any)
    fs << Spree::Core::ProductFilters.select_wing_location_any(self) if Spree::Core::ProductFilters.respond_to?(:select_wing_location_any)
    fs << Spree::Core::ProductFilters.select_main_cups_count_any(self) if Spree::Core::ProductFilters.respond_to?(:select_main_cups_count_any)
    fs << Spree::Core::ProductFilters.select_emb_system_any(self) if Spree::Core::ProductFilters.respond_to?(:select_emb_system_any)
    fs << Spree::Core::ProductFilters.select_connect_diametr_any(self) if Spree::Core::ProductFilters.respond_to?(:select_connect_diametr_any)
    fs << Spree::Core::ProductFilters.select_drain_diametr_any(self) if Spree::Core::ProductFilters.respond_to?(:select_drain_diametr_any)
    fs << Spree::Core::ProductFilters.select_placement_any(self) if Spree::Core::ProductFilters.respond_to?(:select_placement_any)
    fs << Spree::Core::ProductFilters.select_wheelbase_any(self) if Spree::Core::ProductFilters.respond_to?(:select_wheelbase_any)
    fs << Spree::Core::ProductFilters.select_heating_type_any(self) if Spree::Core::ProductFilters.respond_to?(:select_heating_type_any)
    fs << Spree::Core::ProductFilters.select_power_wt_any(self) if Spree::Core::ProductFilters.respond_to?(:select_power_wt_any)
    fs << Spree::Core::ProductFilters.select_tank_vol_any(self) if Spree::Core::ProductFilters.respond_to?(:select_tank_vol_any)
    fs << Spree::Core::ProductFilters.select_heat_element_type_any(self) if Spree::Core::ProductFilters.respond_to?(:select_heat_element_type_any)
    fs << Spree::Core::ProductFilters.select_liner_any(self) if Spree::Core::ProductFilters.respond_to?(:select_liner_any)
    fs << Spree::Core::ProductFilters.select_internal_coating_tank_any(self) if Spree::Core::ProductFilters.respond_to?(:select_internal_coating_tank_any)
    # fs << Spree::Core::ProductFilters.select_equip_any(self) if Spree::Core::ProductFilters.respond_to?(:select_equip_any)
    # fs << Spree::Core::ProductFilters.select_guarantee_any(self) if Spree::Core::ProductFilters.respond_to?(:select_guarantee_any)
    # fs << Spree::Core::ProductFilters.select_napolnoe_any(self) if Spree::Core::ProductFilters.respond_to?(:select_napolnoe_any)
    # fs << Spree::Core::ProductFilters.select_nastennoe_any(self) if Spree::Core::ProductFilters.respond_to?(:select_nastennoe_any)
    # fs << Spree::Core::ProductFilters.select_out_look_any(self) if Spree::Core::ProductFilters.respond_to?(:select_out_look_any)
    # fs << Spree::Core::ProductFilters.select_cap_in_any(self) if Spree::Core::ProductFilters.respond_to?(:select_cap_in_any)
    # fs << Spree::Core::ProductFilters.select_mix_in_any(self) if Spree::Core::ProductFilters.respond_to?(:select_mix_in_any)
    #fs << Spree::Core::ProductFilters.select_type_any(self) if Spree::Core::ProductFilters.respond_to?(:select_type_any)

    fs
  end


  	
end